FROM node:20-alpine AS build

WORKDIR /client

COPY . .

RUN npm install && npm run build

FROM nginx:alpine

COPY --from=build /client/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]