version: "3.9"

services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./api:/api
    command: /usr/bin/supervisord
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=changeme
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=devdb
      - POSTGRES_HOST=postgres-db
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}

  postgres-db:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d postgres"]
      interval: 1s
      timeout: 1s
      retries: 60

  redis:
    image: redis:7.0-alpine
    environment:
      - REDIS_PASSWORD=changeme
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 1s
      retries: 60

volumes:
  postgres-data:
  redis-data:
